---

- name: Non_Compliant_Group
  hosts: web
  vars:
    - goodkernel: 3.10.0-693.17.1.el7.x86_64

  tasks:

    - name: Revalidate2
      setup:
      tags: data_collection

    - name: TheVerdict2
      fail:
        msg: "Confirmed 2x the kernel is not right..."
      when: ansible_kernel != goodkernel
