---

- name: Non_Compliant_Group
  hosts: localhost


  tasks:

    - name: Create_NonCompliant_Tower_Group
      add_host:
        name: NonCompliantKernel
        groups: yes
      tags: CreateGroup
